# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('url', models.URLField(verbose_name='url')),
                ('title', models.CharField(blank=True, max_length=254, verbose_name='title')),
                ('activate_date', models.DateField(blank=True, help_text='keep empty for an immediate activation', verbose_name='activate date')),
                ('deactivate_date', models.DateField(blank=True, help_text='keep empty for indefinite activation', null=True, verbose_name='deactivate date')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
            ],
            options={
                'ordering': ('order', 'status'),
            },
        ),
    ]
